# Generated by Django 5.2 on 2025-04-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='ride.ride')),
            ],
            options={
                'verbose_name': 'Ride Event',
                'verbose_name_plural': 'Ride Events',
                'db_table': 'ride_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
