# Generated by Django 5.2 on 2025-04-17 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('en-route', 'En Route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField()),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='ride.ride')),
            ],
            options={
                'verbose_name': 'Ride Event',
                'verbose_name_plural': 'Ride Events',
                'db_table': 'ride_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='ride_ride_pickup__ffcae2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_latitude', 'pickup_longitude'], name='ride_ride_pickup__8dc0f0_idx'),
        ),
    ]
