# Generated by Django 5.2 on 2025-04-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS cube;",
            reverse_sql="DROP EXTENSION IF EXISTS cube;",
            hints={'target_db': 'default'},
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS earthdistance;",
            reverse_sql="DROP EXTENSION IF EXISTS earthdistance;",
            hints={'target_db': 'default'},
        )
    ]
