# Generated by Django 5.2 on 2025-04-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ride_ride_ride_pickup__ffcae2_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS cube;'),
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS earthdistance;'),
    ]
